#!/bin/bash
gcc -Wall -Wextra -O3 -c curlutil.c -lcurl
gcc -Wall -Wextra -O3 -c gpsutil.c -lgps
gcc -Wall -Wextra -O3 -c shputil.c -lshp
gcc -Wall -Wextra -O3 -c engine.c
gcc -Wall -Wextra -O3 -c rutil.c -lm
gcc -Wall -Wextra -c option.c
gcc -Wall -O3 -c -DGDK_DISABLE_DEPRECATED -DGDK_DISABLE_DEPRECATE show.c $(pkg-config --cflags webkit2gtk-4.0) $(pkg-config --cflags gtk+-3.0)

gcc show.o option.o rutil.o engine.o shputil.o gpsutil.o curlutil.o -o show -lcurl -pthread -lgps -lshp -leccodes -lm $(pkg-config --cflags --libs webkit2gtk-4.0) `pkg-config --cflags --libs gtk+-3.0`

rm -f *.o
mv show ../.



