#!/bin/bash
gcc -Wall -Wextra -pedantic -Werror -Wformat=2 -std=c11 -O2 -c engine.c `pkg-config --cflags glib-2.0`
gcc -Wall -Wextra -pedantic -Werror -Wformat=2 -std=c11 -O1 -c option.c `pkg-config --cflags glib-2.0`
gcc -Wall -Wextra -pedantic -Werror -std=c11 -O2 -c rutil.c `pkg-config --cflags glib-2.0` 
gcc -Wall -Wextra -pedantic -Werror -std=c11 -O2 -c gpsutil.c 
gcc -Wall -Wuninitialized -Wformat=2 -std=c11 -O1 -c show4.c `pkg-config --cflags gtk4`
#gcc -Wformat=2 -std=c11 -O1 -c show4.c `pkg-config --cflags gtk4`
#gcc -Wall -std=c11 -O1 -c show4.c `pkg-config --cflags gtk4` $(pkg-config --cflags webkit2gtk-4.1)

#gcc show4.o option.o rutil.o engine.o -o routing -lcurl -pthread -lgps -lshp -leccodes -lm $(pkg-config --cflags --libs webkit2gtk-4.1) `pkg-config --cflags --libs gtk4`
gcc show4.o option.o rutil.o engine.o gpsutil.o -o routing -std=c11 -lcurl -lgps -lshp -leccodes -lm `pkg-config --cflags --libs gtk4`
# -lnova required if libnova used
rm -f *.o
mv routing ../.

