#!/bin/bash
gcc -Wall -Wextra -pedantic -O3 -c engine.c
gcc -Wall -Wextra -pedantic -c option.c
gcc -Wall -Wextra -pedantic -O3 -c rutil.c `pkg-config --cflags --libs glib-2.0` 
gcc -Wall -pedantic -O3 -c -DGDK_DISABLE_DEPRECATED -DGTK_DISABLE_DEPRECATE show.c $(pkg-config --cflags webkit2gtk-4.1) $(pkg-config --cflags gtk+-3.0)
#gcc -Wall -O3 -c -DPORT=GTK show.c $(pkg-config --cflags webkit2gtk-4.0) $(pkg-config --cflags gtk+-3.0)

gcc show.o option.o rutil.o engine.o -o routing -lcurl -pthread -lgps -lshp -leccodes -lm $(pkg-config --cflags --libs webkit2gtk-4.0) `pkg-config --cflags --libs gtk+-3.0`

rm -f *.o
mv routing ../.



