#!/bin/bash
gcc -Wall -Wextra -O3 -c curlutil.c
gcc -Wall -Wextra -O3 -c gpsutil.c
gcc -Wall -Wextra -O3 -c shputil.c
gcc -Wall -Wextra -O3 -c engine.c
gcc -Wall -Wextra -O3 -c rutil.c
gcc -Wall -Wextra -c option.c
gcc -Wall -O3 -c -DGDK_DISABLE_DEPRECATED show.c $(pkg-config --cflags webkit2gtk-4.0) $(pkg-config --cflags gtk+-3.0)

gcc show.o option.o rutil.o engine.o shputil.o gpsutil.o curlutil.o -o routing -lcurl -pthread -lgps -lshp -leccodes -lm $(pkg-config --cflags --libs webkit2gtk-4.0) `pkg-config --cflags --libs gtk+-3.0`

rm -f *.o
mv routing ../.



