#!/bin/bash
gcc -Wall -Wextra -pedantic -Werror -std=c11 -O2 -c polar.c `pkg-config --cflags glib-2.0` 
gcc -Wall -Wextra -pedantic -Werror -std=c11 -O2 -c r3util.c `pkg-config --cflags glib-2.0` 
gcc -c composepol.c `pkg-config --cflags glib-2.0`

gcc composepol.o polar.o r3util.o -o composepol -std=c11 -lm `pkg-config --cflags --libs glib-2.0`

rm *.o
