#!/bin/bash
CFLAGS="-Wall -Wextra -Wpedantic -Wformat=2 -Wwrite-strings -Wredundant-decls -Wmissing-include-dirs -Wnested-externs -std=c11 -O2"
gcc $CFLAGS -c -O3 engine.c `pkg-config --cflags glib-2.0`
gcc $CFLAGS -c r3grib.c `pkg-config --cflags glib-2.0`
gcc $CFLAGS -c polar.c `pkg-config --cflags glib-2.0`
gcc $CFLAGS -c r3util.c `pkg-config --cflags glib-2.0` 
gcc $CFLAGS -c mailutil.c `pkg-config --cflags glib-2.0` 
gcc $CFLAGS -c r3server.c $(pkg-config --cflags --libs glib-2.0)
#gcc $CFLAGS -Wall -Wextra -pedantic -Werror -Wformat=2 -std=c11 -c rserver.c $(pkg-config --cflags --libs glib-2.0)

gcc r3server.o r3util.o r3grib.o polar.o engine.o mailutil.o -o r3server -std=c11 -leccodes -lm -lcurl `pkg-config --cflags --libs glib-2.0`
rm -f *.o
mv r3server ../.

