#!/bin/bash
gcc -c rserver.c $(pkg-config --cflags --libs glib-2.0)
gcc -Wall -Wextra -pedantic -Werror -Wformat=2 -std=c11 -O2 -c engine.c `pkg-config --cflags glib-2.0`
gcc -Wall -Wextra -pedantic -Werror -Wformat=2 -std=c11 -O1 -c grib.c `pkg-config --cflags glib-2.0`
gcc -Wall -Wextra -pedantic -Werror -Wformat=2 -std=c11 -O1 -c polar.c `pkg-config --cflags glib-2.0`
gcc -Wno-format-nonliteral -c rutil.c `pkg-config --cflags glib-2.0` 

gcc rserver.o rutil.o grib.o polar.o engine.o -o rserver -std=c11 -leccodes -lshp -lm `pkg-config --cflags --libs glib-2.0`
rm -f *.o
mv rserver ../.

# x86_64-w64-mingw32-gcc





