#!/bin/bash
echo "cppcheck"
cppcheck --enable=warning,performance,portability,information,missingInclude *.h
cppcheck --enable=warning,performance,portability,information,missingInclude *.c

echo "gcc analyser"
gcc -fanalyzer -c engine.c `pkg-config --cflags glib-2.0`
gcc -fanalyzer -c rutil.c `pkg-config --cflags glib-2.0`
gcc -fanalyzer -c option.c `pkg-config --cflags glib-2.0`
gcc -fanalyzer -c show4.c `pkg-config --cflags gtk4`
